In [77]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns

In [78]:
dataset = pd.read_csv("Customer_Data_Telecom.csv")
dataset.drop("customerID", axis=1, inplace=True)
dataset.head(10)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,Female,0,No,No,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,Female,0,No,No,10,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,Male,0,No,Yes,62,Yes,No,DSL,Yes,Yes,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

In [79]:
dataset.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [80]:
binary_dict = {'Yes': 1, 'No': 0, 'No phone service': 0, 'No internet service': 0}
binary_columns = ['Partner', 'Dependents', 'PhoneService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling', 'Churn', 'MultipleLines']
dataset[binary_columns] = dataset[binary_columns].replace(binary_dict)
contract_dict = {'Month-to-month': 1, 'One year': 2, 'Two year': 3}
dataset['Contract'] = dataset['Contract'].map(contract_dict)
gender_dict = {'Male': 1, 'Female': 0}
dataset['gender'] = dataset['gender'].map(gender_dict)
dataset.head(10)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,0,DSL,0,1,0,0,0,0,1,1,Electronic check,29.85,29.85,0
1,1,0,0,0,34,1,0,DSL,1,0,1,0,0,0,2,0,Mailed check,56.95,1889.5,0
2,1,0,0,0,2,1,0,DSL,1,1,0,0,0,0,1,1,Mailed check,53.85,108.15,1
3,1,0,0,0,45,0,0,DSL,1,0,1,1,0,0,2,0,Bank transfer (automatic),42.30,1840.75,0
4,0,0,0,0,2,1,0,Fiber optic,0,0,0,0,0,0,1,1,Electronic check,70.70,151.65,1
5,0,0,0,0,8,1,1,Fiber optic,0,0,1,0,1,1,1,1,Electronic check,99.65,820.5,1
6,1,0,0,1,22,1,1,Fiber optic,0,1,0,0,1,0,1,1,Credit card (automatic),89.10,1949.4,0
7,0,0,0,0,10,0,0,DSL,1,0,0,0,0,0,1,0,Mailed check,29.75,301.9,0
8,0,0,1,0,28,1,1,Fiber optic,0,0,1,1,1,1,1,1,Electronic check,104.80,3046.05,1
9,1,0,0,1,62,1,0,DSL,1,1,0,0,0,0,2,0,Bank transfer (automatic),56.15,3487.95,0

In [81]:
one_hot_columns = ['InternetService', 'PaymentMethod'] 
dataset = pd.get_dummies(data=dataset, columns=one_hot_columns, drop_first=False)
dataset = dataset.drop(['InternetService_No', 'PaymentMethod_Mailed check'], axis=1)
dataset.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,Contract,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,InternetService_DSL,InternetService_Fiber optic,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check
0,0,0,1,0,1,0,0,0,1,0,...,1,1,29.85,29.85,0,1,0,0,0,1
1,1,0,0,0,34,1,0,1,0,1,...,2,0,56.95,1889.5,0,1,0,0,0,0
2,1,0,0,0,2,1,0,1,1,0,...,1,1,53.85,108.15,1,1,0,0,0,0
3,1,0,0,0,45,0,0,1,0,1,...,2,0,42.30,1840.75,0,1,0,1,0,0
4,0,0,0,0,2,1,0,0,0,0,...,1,1,70.70,151.65,1,0,1,0,0,1

In [82]:
X = dataset.drop(['Churn', 'TotalCharges'], axis=1)
y = dataset['Churn']

In [83]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

c:\Users\Shrey\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [84]:
print(accuracy_score(y_pred, y_test))

0.7984099943214082